spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager_db
spring.datasource.username=postgres
spring.datasource.password=adil2005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
sping.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect